### ISSUE TITLE
Look at this skid💀

### ISSUE THREAD

**Issue by technicaljicama** [xtekky/TikTok-X-Ladon#1]
https://github.com/jiroawesome/tikapipy
https://github.com/jiroawesome/tikapi

DONT buy it from him hes a skid and all those things got leaked.
So you can get all those things with a little bit of research

**Comment by technicaljicama** [comment]
"- X-App-Log Generator" 
bro...
1. it is NOT called x-app-log.
2. WTH would you "generate" 
3. Basically he doesnt even know what he is doing there

**Comment by xtekky** [comment]
lmaoooo

**Comment by a13xlol** [comment]
> 

uhhh the things you listed are paid too.....

**Comment by xtekky** [comment]
> > 
> 
> 
> 
> uhhh the things you listed are paid too.....

he means the other repo
