### ISSUE TITLE
TikTok did not accept the generated key

### ISSUE THREAD

**Issue by mfoud444** [xtekky/TikTok-X-Ladon#4]
TikTok did not accept the generated key,

1588093228 is bound to aid in douyin not TikTok 

in douyin aid = 1128

in TikTok aid = 1233

how to get correct  value  for TikTok like 1588093228 for douyin?!

**Comment by xtekky** [comment]
should be updated, note that you also need X-Argus

**Comment by mfoud444** [comment]
how to updated?!
